Add user-agent to DummyConfig
Fixes this error while trying to fetch lists:

```
AttributeError: ('intersphinx inventory %r not fetchable due to %s: %s', 'http://docs.python.org/3.8/objects.inv', <class 'AttributeError'>, "'DummyConfig' object has no attribute 'user_agent'")

```